### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by ThomasChilinski** [maxbrunsfeld/atom-nrepl#12]
[Enter steps to reproduce below:]

In termainal
1. lein new app clojure-noob
2. cd into the clojure-noob directory
3. lein repl
4. in atom open core.clj
5. highlight a line
5. press ctrl-alt-e

**Atom Version**: 0.209.0
**System**: Ubuntu 14.04.2
**Thrown From**: [nrepl](https://github.com/maxbrunsfeld/atom-nrepl) package, v0.3.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/thomas/.atom/packages/nrepl/lib/code-manager.coffee:18

TypeError: undefined is not a function
  at namespaceForRange (/home/thomas/.atom/packages/nrepl/lib/code-manager.coffee:18:20)
  at CodeManager.module.exports.CodeManager.currentExpressionWithNamespace (/home/thomas/.atom/packages/nrepl/lib/code-manager.coffee:12:17)
  at Controller.module.exports.Controller.evalCurrentExpression (/home/thomas/.atom/packages/nrepl/lib/controller.coffee:25:31)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "mobile-preview",
      "mobile-preview",
      "mobile-preview",
      "mobile-preview"
    ]
  }
}
```

### Installed Packages

```coffee
# User
browser-plus, v0.0.23
nrepl, v0.3.0

# Dev
No dev packages
```

**Comment by maxbrunsfeld** [comment]
Thanks for the report! Sorry about this. It is fixed in v0.4.

**Comment by ThomasChilinski** [comment]
Thank you for your concern, it no longer throws an exception and is connecting at the right port.

ctrl-alt-e opens a grey box with no cursor.

I'm new to Clojure and Atom. So It's possible I am doing something incorrectly.
(I was expecting a cursor)

Additional Info
********************************************************************************
I am running kernal version 3.16.0-40 Xbuntu
using Nvida binary driver version 331.113

**Comment by maxbrunsfeld** [comment]
There's usually no cursor in the box. It's pretty basic right now: it should just display the value of the highlighted expression (or an error, in the case where the expression threw an error) in the box.

**Comment by ThomasChilinski** [comment]
I see! The return value of print line is nil so i didn't see anything.

When i return from work i will have more time to explore possibilities.


I am looking forward to Clojure in atom. Thank you.
